# Generated by Django 5.1.6 on 2025-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
