# Generated by Django 5.1.6 on 2025-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_app', '0002_note_x_position_note_y_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(default='#FFD700', max_length=7),
        ),
    ]
